-- MySQL Script generated by MySQL Workbench
-- Mon Dec 14 18:14:36 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mybd
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mybd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mybd` DEFAULT CHARACTER SET utf8 ;
USE `mybd` ;

-- -----------------------------------------------------
-- Table `mybd`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mybd`.`user` (
  `id_user` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `place` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_user`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mybd`.`account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mybd`.`account` (
  `tel` INT NOT NULL AUTO_INCREMENT,
  `pass` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`tel`),
  CONSTRAINT `1`
    FOREIGN KEY (`tel`)
    REFERENCES `mybd`.`user` (`id_user`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mybd`.`korzyna`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mybd`.`korzyna` (
  `id_korzyna` INT NOT NULL,
  `tovar` VARCHAR(45) NULL,
  PRIMARY KEY (`id_korzyna`),
  CONSTRAINT `1`
    FOREIGN KEY (`id_korzyna`)
    REFERENCES `mybd`.`user` (`id_user`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mybd`.`tovar na kupivlyu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mybd`.`tovar na kupivlyu` (
  `id_kupivlya` INT NOT NULL,
  `name_kupivyla` VARCHAR(45) NULL,
  `photo_kupivlya` VARCHAR(45) NULL,
  `opys_kupivlya` VARCHAR(45) NULL,
  `price_kupivlya` VARCHAR(45) NULL,
  PRIMARY KEY (`id_kupivlya`),
  INDEX `fk_tovar_korzyna1_idx` (`id_kupivlya` ASC) VISIBLE,
  CONSTRAINT `fk_tovar_korzyna1`
    FOREIGN KEY (`id_kupivlya`)
    REFERENCES `mybd`.`korzyna` (`id_korzyna`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mybd`.`tovar na prodaj`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mybd`.`tovar na prodaj` (
  `id_prodaj` INT NOT NULL,
  `photo_prodaj` VARCHAR(45) NULL,
  `opys_prodaj` VARCHAR(45) NULL,
  `price` VARCHAR(45) NULL,
  `user_id_prodaj` INT NULL,
  `mae akciyu?` INT NULL,
  PRIMARY KEY (`id_prodaj`),
  INDEX `fk_tovar na prodagh_user1_idx` (`user_id_prodaj` ASC) INVISIBLE,
  INDEX `mae alciyu` (`mae akciyu?` ASC) VISIBLE,
  CONSTRAINT `fk_tovar na prodagh_user1`
    FOREIGN KEY (`user_id_prodaj`)
    REFERENCES `mybd`.`user` (`id_user`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mybd`.`akcia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mybd`.`akcia` (
  `id_akcia` INT NOT NULL,
  `zmist_akcia` VARCHAR(45) NULL,
  `data_akcia` DATE NULL,
  PRIMARY KEY (`id_akcia`),
  CONSTRAINT `1`
    FOREIGN KEY (`id_akcia`)
    REFERENCES `mybd`.`tovar na prodaj` (`mae akciyu?`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mybd`.`gift`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mybd`.`gift` (
  `id_gift` INT NOT NULL,
  `photo_gift` VARCHAR(45) NULL,
  `opys_gift` VARCHAR(45) NULL,
  PRIMARY KEY (`id_gift`),
  CONSTRAINT `1`
    FOREIGN KEY (`id_gift`)
    REFERENCES `mybd`.`tovar na kupivlyu` (`id_kupivlya`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
